### ISSUE TITLE
Images stacked over each other when fetched with a promise

### ISSUE THREAD

**Issue by MariusStuparu** [Shailu4u/ng-masonry-grid#16]
Hello,

I am fetching my images data with a get promise in Angular 6, like this:

```typescript
this.getModule.gallery( this.id )
        .then( ( gallery: Gallery ) => {
          this.gallery = gallery;
        } );
```

And in the template:
```html
<ng-masonry-grid [masonryOptions]="gridOptions"
                       [useAnimation]="false"
                       class="imagesGrid"
                       *ngIf="gallery.images">
        <ng-masonry-grid-item *ngFor="let image of gallery.images; let i = index;"
                              id="{{'masonry-item-'+i}}"
                              class="photo gridItem">
          <a (click)="lightbox(image)"><img [src]="image.large" [alt]="image.title" /></a>
</ng-masonry-grid-item>
```

But on first load (I'm guessing before cache is created) the layout is messed up, all rows ar stacked on top of eachother. For example, first row has:
```css
{
margin-bottom: 10px;
position: absolute;
left: 0px;
top: 0px;
}
```
Row 2:
```css
{
margin-bottom: 10px;
position: absolute;
left: 0px;
top: 10px;
}
```
Row 3:
```css
{
margin-bottom: 10px;
position: absolute;
left: 0px;
top: 20px;
}
```

After refresh, the second row item gets this css:
```css
{
margin-bottom: 10px;
position: absolute;
left: 0px;
top: 210.25px;
}
```
